### ISSUE TITLE
USB parallel port error:  Can't negotiate required mode

### ISSUE THREAD

**Issue by humblewizard** [shemanaev/node-lpt#8]
Version, node 6.10.3.  Upon execution:

```
var port = new lpt.Port(0, 'byte', false);
           ^
TypeError: Can't negotiate required mode
    at TypeError (native)
    at Object.<anonymous> (/home/bob/TBinst/AutoPilot.js:2:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

```

My source:
```
var lpt = require('lpt');
var port = new lpt.Port(0, 'byte', false);
port.control.strobe = true;
setInterval(function(){
	port.control.strobe = false;
	setTimeout(function(){
		console.log(port.data);
		port.control.strobe = true;
	},50);	
},300);
```

usb parallel port info:

```
$ lsmod | grep lp
usblp                           22901  0 
lpc_ich                        21093  0 
drm_kms_helper         61574  1 i915
drm                             311018  6 i915,drm_kms_helper
lp                                17759  0 
parport                        42348  3 lp,ppdev,parport_pc
```

**Comment by humblewizard** [comment]
Another piece of information on this. I uninstalled node and all modules and reinstalled  node 0.12 and the modules again. The error looks just about the same. I am using a USB Parallel port which migh be causing the trouble. Here is output from running test code as above:

```
var port = new lpt.Port(0, 'byte', true);
           ^
TypeError: Can't negotiate required mode
    at TypeError (native)
    at Object.<anonymous> (/home/bob/TBinst/AutoPilot.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by humblewizard** [comment]
On another machine with a real parallel port my bit of code runs fine. I guess usb port are out.

**Comment by humblewizard** [comment]
Maybe there exists such a usb-parallel that works.  My research into this says no :(

**Comment by shemanaev** [comment]
Hi. I'm not sure how usb-lpt driver works, but have you looked for `/dev/parportX`? Is there any for usb-lpt? If not, maybe there's device in `/dev/usb/lpX` and you should create symlink `ln -s /dev/usb/lpX /dev/parportX`

**Comment by shemanaev** [comment]
Nevermind. That not gonna work. `usblp` isn't full LPT emulation. It has different API ([c example](https://hackaday.io/project/10512-potentially-usefulobscure-linux-stuff/log/43345-usb-parallel-port-adapter-low-level-coding-usblpc)) and don't allow access to control pins also.
